version: '3'
 
services:
  web:
    container_name: axios-vue-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8081:8080
    volumes:
      - ".:/projects"
    tty: true
 